# ============================================================================
# Data — Aurora PostgreSQL Serverless v2 and ElastiCache Redis
#
# Both live in the isolated subnet tier, which has no route to a NAT or gateway.
# They are unreachable from the internet by construction.
#
# Aurora Serverless v2 rather than provisioned instances: at Step 2 nobody knows
# the real load shape, and Serverless v2 scales between a floor and a ceiling
# without a maintenance window. In dev the floor of 0.5 ACU costs roughly £35/month
# rather than a provisioned instance sitting idle. If a steady load profile emerges
# later, switching to provisioned is a change to this file, not a migration.
# ============================================================================

terraform {
  required_version = ">= 1.10"
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.80" }
  }
}

# ── Variables ───────────────────────────────────────────────────────────────

variable "name_prefix" { type = string }
variable "environment" { type = string }
variable "isolated_subnet_ids" { type = list(string) }
variable "database_security_group_id" { type = string }
variable "cache_security_group_id" { type = string }
variable "data_kms_key_arn" { type = string }
variable "secrets_kms_key_arn" { type = string }

variable "aurora_min_capacity" {
  description = "ACUs. 0.5 is the Serverless v2 floor."
  type        = number
  default     = 0.5
}

variable "aurora_max_capacity" {
  description = "ACU ceiling. Acts as a cost guard as much as a capacity limit."
  type        = number
  default     = 4
}

variable "aurora_instance_count" {
  description = "1 in dev. At least 2 in prod so a failover has somewhere to go."
  type        = number
  default     = 1
}

variable "cache_node_type" {
  type    = string
  default = "cache.t4g.micro"
}

variable "cache_replica_count" {
  description = "0 in dev. At least 1 in prod for automatic failover."
  type        = number
  default     = 0
}

variable "tags" {
  type    = map(string)
  default = {}
}

locals {
  is_production = var.environment == "prod"
}

# ── Aurora PostgreSQL ───────────────────────────────────────────────────────

resource "aws_db_subnet_group" "this" {
  name       = "${var.name_prefix}-aurora"
  subnet_ids = var.isolated_subnet_ids
  tags       = merge(var.tags, { Name = "${var.name_prefix}-aurora" })
}

resource "aws_rds_cluster_parameter_group" "this" {
  name   = "${var.name_prefix}-aurora-pg16"
  family = "aurora-postgresql16"

  # Reject any connection that is not TLS. Application connection strings must
  # therefore set SSL Mode=Require, which is the correct default anyway.
  parameter {
    name         = "rds.force_ssl"
    value        = "1"
    apply_method = "pending-reboot"
  }

  # Log statements slower than 1s. Enough to catch a missing index before it
  # becomes an incident, quiet enough not to fill the log group.
  parameter {
    name  = "log_min_duration_statement"
    value = "1000"
  }

  parameter {
    name  = "log_connections"
    value = "1"
  }

  # pg_stat_statements is how you answer "what is slow" without guessing.
  parameter {
    name         = "shared_preload_libraries"
    value        = "pg_stat_statements"
    apply_method = "pending-reboot"
  }

  tags = var.tags
}

resource "aws_rds_cluster" "this" {
  cluster_identifier = "${var.name_prefix}-aurora"
  engine             = "aurora-postgresql"
  engine_mode        = "provisioned"
  engine_version     = "16.6"

  database_name = "socialremit"

  # Master credentials are generated by RDS and stored in Secrets Manager by RDS.
  # The alternative — a random_password resource — writes the password into
  # Terraform state in plain text, where it is readable by anyone with state access.
  master_username             = "srmaster"
  manage_master_user_password = true
  master_user_secret_kms_key_id = var.secrets_kms_key_arn

  db_subnet_group_name            = aws_db_subnet_group.this.name
  vpc_security_group_ids          = [var.database_security_group_id]
  db_cluster_parameter_group_name = aws_rds_cluster_parameter_group.this.name

  storage_encrypted = true
  kms_key_id        = var.data_kms_key_arn

  backup_retention_period      = local.is_production ? 35 : 7
  preferred_backup_window      = "02:00-03:00"
  preferred_maintenance_window = "sun:03:30-sun:04:30"
  copy_tags_to_snapshot        = true

  deletion_protection       = local.is_production
  skip_final_snapshot       = !local.is_production
  final_snapshot_identifier = local.is_production ? "${var.name_prefix}-aurora-final-${formatdate("YYYYMMDDhhmmss", timestamp())}" : null

  # Postgres logs to CloudWatch. Without this the logs stay on the instance and
  # are lost when it is replaced — including the slow queries you need after an
  # incident.
  enabled_cloudwatch_logs_exports = ["postgresql"]

  serverlessv2_scaling_configuration {
    min_capacity = var.aurora_min_capacity
    max_capacity = var.aurora_max_capacity
  }

  lifecycle {
    # final_snapshot_identifier uses timestamp(), which changes on every plan.
    # Without this the cluster shows a spurious diff forever.
    ignore_changes = [final_snapshot_identifier]
  }

  tags = merge(var.tags, { Name = "${var.name_prefix}-aurora" })
}

resource "aws_rds_cluster_instance" "this" {
  count = var.aurora_instance_count

  identifier         = "${var.name_prefix}-aurora-${count.index}"
  cluster_identifier = aws_rds_cluster.this.id
  instance_class     = "db.serverless"
  engine             = aws_rds_cluster.this.engine
  engine_version     = aws_rds_cluster.this.engine_version

  performance_insights_enabled    = true
  performance_insights_kms_key_id = var.data_kms_key_arn
  monitoring_interval             = 60
  monitoring_role_arn             = aws_iam_role.rds_monitoring.arn

  auto_minor_version_upgrade = true

  tags = merge(var.tags, { Name = "${var.name_prefix}-aurora-${count.index}" })
}

resource "aws_iam_role" "rds_monitoring" {
  name = "${var.name_prefix}-rds-monitoring"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "monitoring.rds.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })

  tags = var.tags
}

resource "aws_iam_role_policy_attachment" "rds_monitoring" {
  role       = aws_iam_role.rds_monitoring.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole"
}

# ── ElastiCache Redis ───────────────────────────────────────────────────────
#
# Redis holds only rate-limit counters and short-lived caches. Nothing that must
# survive a restart lives here — idempotency records and outbox rows are in
# Postgres precisely because Redis evicts under memory pressure.

resource "aws_elasticache_subnet_group" "this" {
  name       = "${var.name_prefix}-redis"
  subnet_ids = var.isolated_subnet_ids
  tags       = var.tags
}

resource "aws_elasticache_parameter_group" "this" {
  name   = "${var.name_prefix}-redis7"
  family = "redis7"

  # Evict the least-recently-used key with a TTL rather than refusing writes.
  # Refusing writes would fail rate limiting closed and lock customers out.
  parameter {
    name  = "maxmemory-policy"
    value = "volatile-lru"
  }

  tags = var.tags
}

resource "aws_elasticache_replication_group" "this" {
  replication_group_id = "${var.name_prefix}-redis"
  description          = "Social Remit ${var.environment} cache and rate-limit counters"

  engine         = "redis"
  engine_version = "7.1"
  node_type      = var.cache_node_type
  port           = 6379

  num_cache_clusters         = 1 + var.cache_replica_count
  automatic_failover_enabled = var.cache_replica_count > 0
  multi_az_enabled           = var.cache_replica_count > 0

  subnet_group_name  = aws_elasticache_subnet_group.this.name
  security_group_ids = [var.cache_security_group_id]
  parameter_group_name = aws_elasticache_parameter_group.this.name

  at_rest_encryption_enabled = true
  kms_key_id                 = var.data_kms_key_arn
  transit_encryption_enabled = true

  # AUTH token is generated and stored out of band, same reasoning as the Aurora
  # master password. See modules/security.
  auth_token_update_strategy = "ROTATE"

  snapshot_retention_limit = local.is_production ? 7 : 0
  maintenance_window       = "sun:04:30-sun:05:30"
  apply_immediately        = !local.is_production

  lifecycle {
    ignore_changes = [auth_token]
  }

  tags = merge(var.tags, { Name = "${var.name_prefix}-redis" })
}

# ── Alarms ──────────────────────────────────────────────────────────────────

variable "alarm_topic_arn" {
  description = "SNS topic for alarm notifications"
  type        = string
}

resource "aws_cloudwatch_metric_alarm" "aurora_cpu" {
  alarm_name          = "${var.name_prefix}-aurora-cpu-high"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 3
  metric_name         = "CPUUtilization"
  namespace           = "AWS/RDS"
  period              = 300
  statistic           = "Average"
  threshold           = 80
  alarm_description   = "Aurora CPU sustained above 80% — check for a missing index or a runaway query."
  alarm_actions       = [var.alarm_topic_arn]

  dimensions = { DBClusterIdentifier = aws_rds_cluster.this.cluster_identifier }
  tags       = var.tags
}

resource "aws_cloudwatch_metric_alarm" "aurora_capacity_ceiling" {
  alarm_name          = "${var.name_prefix}-aurora-at-max-capacity"
  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = 3
  metric_name         = "ServerlessDatabaseCapacity"
  namespace           = "AWS/RDS"
  period              = 300
  statistic           = "Average"
  threshold           = var.aurora_max_capacity * 0.95
  alarm_description   = "Aurora is pinned at its ACU ceiling. It cannot scale further — raise the ceiling or find the load."
  alarm_actions       = [var.alarm_topic_arn]

  dimensions = { DBClusterIdentifier = aws_rds_cluster.this.cluster_identifier }
  tags       = var.tags
}

resource "aws_cloudwatch_metric_alarm" "redis_evictions" {
  alarm_name          = "${var.name_prefix}-redis-evictions"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "Evictions"
  namespace           = "AWS/ElastiCache"
  period              = 300
  statistic           = "Sum"
  threshold           = 0
  alarm_description   = "Redis is evicting keys. Rate-limit counters may be disappearing early, which weakens abuse protection."
  alarm_actions       = [var.alarm_topic_arn]

  dimensions = { ReplicationGroupId = aws_elasticache_replication_group.this.replication_group_id }
  tags       = var.tags
}

# ── Outputs ─────────────────────────────────────────────────────────────────

output "cluster_endpoint" {
  description = "Writer endpoint"
  value       = aws_rds_cluster.this.endpoint
}

output "cluster_reader_endpoint" {
  value = aws_rds_cluster.this.reader_endpoint
}

output "database_name" { value = aws_rds_cluster.this.database_name }

output "master_secret_arn" {
  description = "RDS-managed master credentials. Used only by migration tasks, never by a service."
  value       = aws_rds_cluster.this.master_user_secret[0].secret_arn
}

output "redis_primary_endpoint" {
  value = aws_elasticache_replication_group.this.primary_endpoint_address
}

output "redis_reader_endpoint" {
  value = aws_elasticache_replication_group.this.reader_endpoint_address
}
